### ISSUE TITLE
FIx Iso Paja list by supporting image to text scraping

### ISSUE THREAD

**Issue by joonasmkauppinen** [joonasmkauppinen/yle-campus-lunch-list#33]
## Details 

[Iso Paja](https://www.hhravintolat.fi/iso-paja) updated their site to only have the lunch list as an image. Need to add support for image to text get it back to working.

Trying to use [Tesseract.js](https://github.com/naptha/tesseract.js/) to handle the image to text genereation.

**Comment by gnizhak** [comment]
Ei kantsi laittaa liikaa vaivaa tähän: 

Annoin palautetta listan saavutettavuudesta ja sain takaisin viestin: 

Hei Ilari,
kiitos palautteestasi.
Iloksesi voin ilmoittaa, että olemme jo käynnistäneet prosessin sivun ruokalistan palauttamiseksi vanhaan muotoon ja asiasta on otettu yhteyttä sivuston rakentamisen hallitsevaan tahoon.

**Comment by joonasmkauppinen** [comment]
@gnizhak Kiitos infosta! Ja mahtavaa, että reagoivat näin saavutettavuus palautteeseen 🙌🏼
